version:  '3'
services:
  db:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
    - db-data:/var/lib/mysql
    ports:
    - 3307:3306
  web:
    build: ./docker
    volumes:
    - ./:/var/www/html/
    - web-var-data:/var/www/html/var
    - web-vendor-data:/var/www/html/vendor
    ports:
    - 80:80
volumes:
  db-data:
  web-var-data:
  web-vendor-data: